### ISSUE TITLE
HTML parsing support

### ISSUE THREAD

**Issue by rafaelmenta** [FezVrasta/snackbarjs#13]
When I try to insert HTML syntax on content it first loads fine as on this [screenshot](https://www.dropbox.com/s/pe0msltfnps7spr/Screenshot%202015-02-08%2021.50.58.png?dl=0)

On the second time I load the same content, HTML content is being rendered as [plain text](https://www.dropbox.com/s/ejddspsik1ddwu2/Screenshot%202015-02-08%2021.56.08.png?dl=0)

I didn't see any reference for HTML rendering on documentation but I believe a better support on it would be a good enhancement

**Comment by FezVrasta** [comment]
Yes I see where is the problem. Will fix it soon

**Comment by rafaelmenta** [comment]
Thank you! I appreciate the quick response

**Comment by FezVrasta** [comment]
Should be fixed, please let me know.

**Comment by rafaelmenta** [comment]
Worked fine, thanks!

Just a quick note, it seems bower was not updated yet, I had to manually pull it :)

**Comment by FezVrasta** [comment]
Yes I was waiting you feedback
