### ISSUE TITLE
Make error only show one message if repeated error is shown

### ISSUE THREAD

**Issue by rollrockofficial** [FezVrasta/snackbarjs#28]
I have a login feature and if the wrong credentials are entered, it will show a error message from snackbarjs. If you click login multiple times, the errors just stack on top of eachother which gives an un-wanted look.

Is there a way to make snackbarjs only show one error if the same error is clicked?

**Comment by ShashankaNataraj** [comment]
How about hiding the previous snackbar and then showing the next one programmatically? Doesnt that solve your issue?

**Comment by rollrockofficial** [comment]
@ShashankaNataraj Yes and no. I still want the messages to stack if they are a success or error, just not repeated errors... It could be an easy fix, I am just having a hard time thinking how to do it. I am using SnackbarJS alongside AngularJS.

**Comment by ShashankaNataraj** [comment]
@rollrockofficial Well, snackbar doesn't currently keep track of messages which were already shown. Would be fairly easy to add, but I think this is an unnecessary overhead on the library. How about keeping track of the error messages in your implementation? Maybe like an array or something which keeps track of errors and other messages and then purges them when something different comes along? Just a thought.

**Comment by FezVrasta** [comment]
You may directly check the jquery object provided by snackbarjs I think... use it to fetch the text inside it so you can know what kind of message you have spawned previously
