### ISSUE TITLE
position of snackbar

### ISSUE THREAD

**Issue by bgrayburn** [FezVrasta/snackbarjs#29]
Would love to be able to specify the position of the snackbar/toast to be top right. Thanks for this great library!

**Comment by FezVrasta** [comment]
You can use css to do it.

**Comment by bgrayburn** [comment]
i appreciate it, seems obvious now, thanks for the response, feel free to
close

**Comment by ShashankaNataraj** [comment]
@FezVrasta This issue can be closed!
