### ISSUE TITLE
Stalled animations when using jquery slimscroll and when pointer is not moved

### ISSUE THREAD

**Issue by zekedran** [FezVrasta/snackbarjs#34]
When [slimscroll](https://plugins.jquery.com/slimScroll) jquery plugin is used, and when the mouse pointer is not moved after the click, the snackbar doesn't appear at all. When slightly moved and left stationary soon after the snackbar is triggered (by clicking a span/div) the snackbar appears, however it doesn't disappear until the mouse is moved. Looks like the animations stall when the pointer isn't moving, while the actions are still getting triggered.

**Comment by zekedran** [comment]
Tried replacing `body` with `html` in snackbar.js, since slimScroll wraps `<body>` into another div with id `slimScrollDiv`
    $(document).ready(function() {
        $("html").append("<div id=snackbar-container/>");
    });

Appearance is fine, but it doesn't disappear

**Comment by zekedran** [comment]
Surprisingly whenever I try to trace this out with the console open and particularly with the `<div id="snackbar-container"> expanded, it works fine.

**Comment by FezVrasta** [comment]
Please provide some kind of live demo.

**Comment by zekedran** [comment]
Watch this [screencast](https://onedrive.live.com/redir?resid=E4B961664BF56C94!2957&authkey=!AFBVpIAlfNcL4wI&ithint=file%2cflv). 

The console remains open and snackbar div being collapsed & NOT focused -> Doesn't work without mouse actions or keypress. (Demonstrated in video)
The console is open and snackbar div is expanded & focused -> Mysteriously, it just works.

**Comment by FezVrasta** [comment]
I need a demo to inspect

**Comment by zekedran** [comment]
Here's [something](https://onedrive.live.com/redir?resid=E4B961664BF56C94!2958&authkey=!AIdC90vVWGatxWw&ithint=file%2czip) on which you can do some testing and inspection
