### ISSUE TITLE
Container Width is not adaptive

### ISSUE THREAD

**Issue by amigoow** [FezVrasta/snackbarjs#39]
If I display a message which is long enough the snackbar displays and it's width changes according to that long text.

Afterwards showing some other content with some short text the width of container remains the width which was previously done with long text.

It's not adaptive width anymore. I have tried using display:inline-block but no joy. Any suggestions?

**Comment by FezVrasta** [comment]
May you provide a codepen of the problem?

**Comment by FezVrasta** [comment]
Closing for lack of reply
