### ISSUE TITLE
Add Show-On-Load option

### ISSUE THREAD

**Issue by paranoid-android** [FezVrasta/snackbarjs#42]
I really like snackbarjs. However, sometimes, I need to toast or snackbar to appear when my page loads. I think it would be useful if a `data-show-on-load` option was added. By default, this attribute would be false. However, when set to true, the snackbar would be visible when the control was initialized.

**Comment by FezVrasta** [comment]
I think you should call your snackbar trough JavaScript instead of relying on the attributes.

It's not the purpose of the attributes initialization the one you ask for.
