### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mbrevda** [FezVrasta/snackbarjs#43]
On larger screens, when using an RTL language such as Hebrew or Arabic, the proper placement of the snackbar would be adjacent to the right side of the screen. The simplest way to account for this would probably be to look for `dir="rtl"` on the `body` and switch [`left`](https://github.com/FezVrasta/snackbarjs/blob/master/src/snackbar.less#L4) to right.

**Comment by FezVrasta** [comment]
Not supported, feel free to send a PR
