### ISSUE TITLE
Snackbar design messed up

### ISSUE THREAD

**Issue by jofftiquez** [FezVrasta/snackbarjs#46]
I installed `snackbarjs` and even tried to download the zip file directly, I am 100% sure that the `js` file and `css` are properly in place, but somehow when I try to do the demo :

`<span data-toggle=snackbar data-content="This is my awesome snackbar!">Click me</span>`

It just shows this output. 

![selection_205](https://cloud.githubusercontent.com/assets/8638243/17832014/b5e93c9a-672b-11e6-82f0-55c60f9d7ccb.png)

No design at all. Am I missing something?

**Comment by FezVrasta** [comment]
Sorry I can't help you if you don't provide a CodePen demo of the problem. By the way I'm quite confident  you are doing something wrong. Check your console, there will probably be some error

**Comment by jofftiquez** [comment]
Does this library require the `bootstrap-material-design`

**Comment by FezVrasta** [comment]
no

**Comment by FezVrasta** [comment]
Make sure to include at least one theme (e.g. https://github.com/FezVrasta/snackbarjs/blob/master/themes-css/material.css)

**Comment by jofftiquez** [comment]
Ok that did it. Thanks! Im sorry for the trouble. @FezVrasta
