### ISSUE TITLE
Buggy with Turbolinks

### ISSUE THREAD

**Issue by hudadiaz** [FezVrasta/snackbarjs#55]
Snackbarjs is defined and run well but does not append the snackbars after page change on Turbolink app.

**Comment by FezVrasta** [comment]
I have no idea what are you talking about. Provide a codepen or something so that others can see the problem and attempt to fix it.

**Comment by hudadiaz** [comment]
The snackbars are no longer being appended to body after a page change through Turbolinks. Apparently, the `div#snackbar-container` is removed after a page change.

**Comment by hudadiaz** [comment]
Fixed it by appending `div#snackbar-container` to body if it doesn't exist on `turbolinks:load`
