### ISSUE TITLE
Snackbar cdn

### ISSUE THREAD

**Issue by OSN64** [FezVrasta/snackbarjs#7]
Just wanted to ask if snackbar should be uploaded to a cdn.

**Comment by kmmbvnr** [comment]
+1

**Comment by ashokfernandez** [comment]
+1

**Comment by FezVrasta** [comment]
It's already on bower

**Comment by ashokfernandez** [comment]
Whoops, I was trying ```bower install snackbar`` not ```bower install snackbarjs```

**Comment by lahdo** [comment]
Unfortunately Bower is installing 2 years old version of snackbarjs.

**Comment by FezVrasta** [comment]
I've released a new version which should affect both npm and bower
