### ISSUE TITLE
When multiple snackbars are displayed, incorrect one dismissed on click.

### ISSUE THREAD

**Issue by Schnyder** [FezVrasta/snackbarjs#8]
I've run into an issue where if I have several snackbars displayed simultaneously (with 0 duration in my case), clicking on one will frequently result in the dismissal of one of the NON-clicked snackbars.  My expectation would be that the clicked snackbar is dismissed.

**Comment by FezVrasta** [comment]
Will look into this.

**Comment by felixcheruiyot** [comment]
Any update on this issue?

**Comment by FezVrasta** [comment]
I've not time to study the problem, I will probably start using this library in the next weeks and I'll improve it.

**Comment by FezVrasta** [comment]
I can't reproduce it, may you provide a codepen demo?
